//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionSQL_webAPI_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorBelongsHospital
    {
        public int DoctorBelongsHospitalId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> HospitaId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DoctorInfo DoctorInfo { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
